spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: user
    password: 123456
    url: 'jdbc:mysql://106.52.73.136:3306/userdb?useUnicode=true&characterEncoding=UTF-8'
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
pagehelper:
  helper-dialect: mysql
  reasonable: true
      
        
